export const UPDATE_AXIOS: string = 'UPDATE_AXIOS'
export const INIT_BREEDS: string = 'INIT_BREEDS'
export const INIT_CATEGORIES: string = 'INIT_CATEGORIES'

export const INIT_SETTING_BREEDS: string = 'INIT_SETTING_BREEDS'
export const INIT_SETTING_CATEGORIES: string = 'INIT_SETTING_CATEGORIES'
export const UPDATE_SETTING_TYPE: string = 'UPDATE_SETTING_TYPE'
export const UPDATE_SETTING_BREEDS: string = 'UPDATE_SETTING_BREEDS'
export const UPDATE_SETTING_CATEGORIES: string = 'UPDATE_SETTING_CATEGORIES'
